feat: Parameters for file icon height and v-adjust
emacs-dashboard/emacs-dashboard pull request #546
Opened 2024-09-24 18:00 UTC by christoffer-arvidsson

This PR adds support for tweaking the height and v-adjust of file icons. It aligns with the existing parameters
`dashboard-heading-icon-height` and `dashboard-heading-icon-v-adjust` which work similarly for heading icons.

Defaults are set to the previous defaults.

Let me know if there are any changes needed. :slightly_smiling_face:

2024-09-24 18:13 UTC, ricardoricho requested changes
Thanks for your PR. There is also a `dashboard-icon-for-file`. Should we have `dashboard-icon-dir-height` and `dashboard-icon-dir-v-adjust`, or could we use only one `dashboard-icon-height` and `dashboard-icon-v-adjust` for both?

2024-09-24 18:13 UTC, ricardoricho commented on dashboard-widgets.el
> +(defcustom dashboard-file-icon-height 1.0
I suggest `dashboard-icon-file-height` because is a custom of `dashboard-icon` family ¿?

2024-09-24 18:13 UTC, ricardoricho commented on dashboard-widgets.el
> +(defcustom dashboard-file-icon-v-adjust -0.05
My suggestion is `dashboard-icon-file-v-adjust`

2024-09-29 07:59 UTC, christoffer-arvidsson commented
> Thanks for your PR. There is also a `dashboard-icon-for-file`. Should we have `dashboard-icon-dir-height` and `dashboard-icon-dir-v-adjust`, or could we use only one `dashboard-icon-height` and `dashboard-icon-v-adjust` for both?

I think that's sensible. One issue might be that the there's already different v-adjusts for the different icons used `-0.05` for file, `0.01` for others. It looked fine for me to set these to the same with the exception of the footer which could get the same treatment as heading if needed.

It could be nice to try to organize this a bit better before someone starts customizing them?

2025-02-11 20:32 UTC, jcs090218 commented
I think it makes sense just to have the `-file` variables since there is only `dashboard-set-file-icons` and no `dashboard-set-dir-icons`.

2025-02-11 20:37 UTC, jcs090218 commented
Can you update the REAMDE as well? Thanks!

2025-02-12 16:53 UTC, christoffer-arvidsson commented
@jcs090218 good catch. dir/remote is now handled too. I also updated the README as you requested (hopefully in a good place).

2025-02-12 19:19 UTC, jcs090218 approved these changes

2025-02-12 19:25 UTC, merged

2025-02-12 19:25 UTC, jcs090218 commented
Thank you for taking care of this!  🚀